apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
    version: blue  # Change to 'green' to switch to the green deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer